const stays = [
  {
    _id: utilService.makeId(),
    name: 'Bora Bora bungalow N421 DTO-MT',
    type: 'Entire bungalow',
    imgUrls: [
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638648400/bora%20bora/apt3/1_gbjhmh.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638648400/bora%20bora/apt3/2_la9os5.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638648399/bora%20bora/apt3/3_ep1qfq.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638648399/bora%20bora/apt3/4_rwlxqp.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638648399/bora%20bora/apt3/5_j9gf2l.jpg',
    ],
    price: '185',
    avgRate: '4.8',
    summary:
      'Bungalow avec vue sur lagon et accès direct à la mer. Idéal pour couple souhaitant visiter notre belle île tout en se sentant comme chez eux.',
    capacity: '2',
    amenities: [
      'Kitchen',
      'Wifi',
      'TV',
      'Crib',
      'Smoking allowed',
      'No smoking',
      'Pets allowed',
      'Cooking basics',
      'Air conditioning',
      'Refrigerator',
      'Free parking',
      'Bathub',
      'Elevator',
      'Iron',
      'Heating',
      'Pool',
      'Spa',
      'Bath',
      'Accessible',
      'Beach',
      'Long term stays allowed',
    ],
    host: {
      _id: 'bor101',
      fullname: 'Hitiura & Lionel',
      imgUrl:
        'https://res.cloudinary.com/disku3v4j/image/upload/v1638648400/bora%20bora/apt3/sdv_ffmara.jpg',
    },
    loc: {
      city: 'Bora Bora',
      countryCode: 'BV',
      address: 'Bora Bora, Island in French Polynesia',
      lat: -16.53331046857574,
      lng: -151.74018147397715,
    },
    reviews: [
      {
        id: utilService.makeId(),
        createdAt: 'November  2021',
        txt: 'This is a an adorable home, and looks just like the pictures. There are all very nice neighbors around the home, who brought us candy on Halloween',
        rate: 4.5,
        by: {
          _id: 'us888',
          fullname: 'Lindsey James',
          imgUrl:
            'https://res.cloudinary.com/disku3v4j/image/upload/v1638648399/bora%20bora/apt3/df_grwuti.jpg',
        },
      },
    ],
    likedByUsers: [],
  },
  {
    _id: utilService.makeId(),
    name: "Âlani Punalu'u Black Sand Beach oceanview retreat",
    type: 'Entire condo',
    imgUrls: [
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638649316/bora%20bora/apt4/1_bhmitq.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638649315/bora%20bora/apt4/2_eqkhhf.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638649316/bora%20bora/apt4/3_f86rss.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638649315/bora%20bora/apt4/4_jhcysw.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638649315/bora%20bora/apt4/5_skghzd.jpg',
    ],
    price: '137',
    avgRate: '4.9',
    summary:
      "Serene, remote, zen retreat most scenic places, K’au region at Punalu'u Black Sand Beach. Its a short 1/3 mile walk to the beach, crashing waves, palm trees & flowers, amazing mountain and ocean views, in the countryside of macademia nut & coffee farms",
    capacity: '2',
    amenities: [
      'Kitchen',
      'Wifi',
      'TV',
      'Smoking allowed',
      'Pets allowed',
      'Cooking basics',
      'Air conditioning',
      'Refrigerator',
      'Free parking',
      'Heating',
      'Pool',
      'Spa',
      'Bath',
      'Accessible',
      'Beach',
      'Long term stays allowed',
    ],
    host: {
      _id: 'us110',
      fullname: 'Joe Black',
      imgUrl:
        'https://res.cloudinary.com/disku3v4j/image/upload/v1638649316/bora%20bora/apt4/dfg_occksy.jpg',
    },
    loc: {
      city: 'Hawaii',
      countryCode: 'US-HI',
      address: 'Hawaii, Western United States',
      lat: 19.433138705620028,
      lng: -155.6005259106364,
    },
    reviews: [
      {
        id: utilService.makeId(),
        createdAt: 'November  2021',
        txt: 'This was a perfect spot for a relaxing getaway. The unit is well-equipped and so comfortable. We had the best nights sleeps, and the most relaxing patio breakfasts! The views are amazing and the location is perfect. Would stay again.',
        rate: 4.7,
        by: {
          _id: 'us999',
          fullname: 'Erica Meigs',
          imgUrl:
            'https://res.cloudinary.com/disku3v4j/image/upload/v1638649315/bora%20bora/apt4/asf_ilcd9z.jpg',
        },
      },
    ],
    likedByUsers: [],
  },
  {
    _id: utilService.makeId(),
    name: 'Kūono',
    type: 'Entire cabin',
    imgUrls: [
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638650144/bora%20bora/apt5/1_p9rzr3.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638650143/bora%20bora/apt5/2_gq0zyj.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638650143/bora%20bora/apt5/3_zwpcjf.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638650143/bora%20bora/apt5/4_dkskve.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638650143/bora%20bora/apt5/5_lytyk4.jpg',
    ],
    price: '380',
    avgRate: '4.9',
    summary:
      'Set out on an adventure and return to a retreat of peace and relaxation just five minutes from  National Park',
    capacity: '4',
    amenities: [
      'Kitchen',
      'Wifi',
      'TV',
      'Crib',
      'Smoking allowed',
      'No smoking',
      'Pets allowed',
      'Cooking basics',
      'Air conditioning',
      'Refrigerator',
      'Free parking',
      'Bathub',
      'Elevator',
      'Iron',
      'Heating',
      'Pool',
      'Spa',
      'Bath',
      'Accessible',
      'Beach',
      'Long term stays allowed',
    ],
    host: {
      _id: 'us789',
      fullname: 'Jeff Thomas',
      imgUrl:
        'https://res.cloudinary.com/disku3v4j/image/upload/v1638650143/bora%20bora/apt5/images_1_uohumv.jpg',
    },
    loc: {
      city: 'Hawaii',
      countryCode: 'US-HI',
      address: 'Hawaii, Western United States',
      lat: 19.433138705620028,
      lng: -155.6005259106364,
    },
    reviews: [
      {
        id: utilService.makeId(),
        createdAt: '2021',
        txt: 'A delightful cabin - every detail in perfect shape. The Cedar Hot Tub was so relaxing - the bed extremely comfortable',
        rate: 0,
        by: {
          _id: 'us909',
          fullname: 'Hope Malclom',
          imgUrl:
            'https://res.cloudinary.com/disku3v4j/image/upload/v1638650144/bora%20bora/apt5/images_j472zv.jpg',
        },
      },
    ],
    likedByUsers: [],
  },
  {
    _id: utilService.makeId(),
    name: "Cabane Drommen - L'Arbre à Cabane",
    type: 'Treehouse',
    imgUrls: [
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638651498/exotic/apt1/1_mw7evu.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638651497/exotic/apt1/2_qg4wo3.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638651497/exotic/apt1/3_b3koxb.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638651497/exotic/apt1/4_idi3cd.jpg',
      'https://res.cloudinary.com/disku3v4j/image/upload/v1638651497/exotic/apt1/5_ej6xvk.jpg',
    ],
    price: '72',
    avgRate: '4.7',
    summary:
      'Discover the magical world of the Drommen hut, unique in France. With 4 levels : the living room, then the toilet, then the bedroom. Guests can dine on the perched terrace.',
    capacity: '2',
    amenities: [
      'Kitchen',
      'TV',
      'No smoking',
      'Pets allowed',
      'Cooking basics',
      'Refrigerator',
    ],
    host: {
      _id: 'fr666',
      fullname: 'Jean-Marie',
      imgUrl:
        'https://res.cloudinary.com/disku3v4j/image/upload/v1638651497/exotic/apt1/pexels-photo-3310695_ixtxwp.jpg',
    },
    loc: {
      city: 'France',
      countryCode: 'FR',
      address: 'Guyonvelle, Grand Est, France',
      lat: 49.29615379837761,
      lng: 4.7569801709695145,
    },
    reviews: [
      {
        id: utilService.makeId(),
        createdAt: '2021',
        txt: 'Very friendly and attentive host. Very pleasant cabins and small terrace !!!',
        rate: 4.5,
        by: {
          _id: 'us320948',
          fullname: 'Amélie Patrice',
          imgUrl:
            'https://res.cloudinary.com/disku3v4j/image/upload/v1638651496/exotic/apt1/images_p1mxhv.jpg',
        },
      },
    ],
    likedByUsers: [],
  },
];
